// https://wiki.openstreetmap.org/wiki/Overpass_API#The_Programmatic_Query_Language_(OverpassQL)
// https://overpass-turbo.eu/ Wizard is very helpful for generating queries
// Note that the wizard may use https://wiki.openstreetmap.org/wiki/Overpass_turbo/Extended_Overpass_Turbo_Queries, which are not accepted by Overpass API proper

export class OverpassClient {


    /*
        
        This has been generated by the overpass-turbo wizard.
        The original search was:
        “amenity=restaurant around "655 Broadview, Toronto, Ontario"”
        
        [out:json][timeout:25];
        // adjust the search radius (in meters) here
        {{radius=1000}}
        // gather results
        nwr["amenity"="restaurant"](around:{{radius}},{{geocodeCoords:655 Broadview, Toronto, Ontario}});
        // print results
        out geom;

    */

    // TODO: Try Nominatim https://nominatim.org/release-docs/latest/api/Search/
    static async getCoordsFromAddress(address: string) {
        var result = await fetch(
            "https://overpass-api.de/api/interpreter",
            {
                method: "POST",
                body: "data=" + encodeURIComponent(`
                    [out:json];
                    node(around:1000, {{geocodeCoords:655 Broadview Ave, Toronto, Ontario}})[amenity=restaurant];
                    out;
                `)
            },
        );

        const resultText = await result.text();

        try {
            return JSON.parse(resultText);
        } catch (e) {
            console.error("Response wasn't json");
            return resultText;
        }
    };

    static async getRestaurantsAroundAddress() {
        var result = await fetch(
            "https://overpass-api.de/api/interpreter",
            {
                method: "POST",
                body: "data=" + encodeURIComponent(`
                    [out:json];
                    node(around:1000, {{geocodeCoords:655 Broadview Ave, Toronto, Ontario}})[amenity=restaurant];
                    out;
                `)
                // body: "data=" + encodeURIComponent(`
                // [out:json][timeout:25];
                // {{radius=1000}}
                // nwr["amenity"="restaurant"](around:{{radius}},{{geocodeCoords:655 Broadview, Toronto, Ontario}});
                // out;
                // `)
                // body: "data=" + encodeURIComponent(`
                //     [out:json][timeout:25];
                //     {{radius=1000}}
                //     nwr["amenity"="restaurant"](around:1000,43.676173, -79.358705);
                //     out;
                // `)
            },
        );


        const resultText = await result.text();

        try {
            return JSON.parse(resultText);
        } catch (e) {
            console.error("Response wasn't json");
            return resultText;
        }
    };

    static async getRestaurantsByGPS(lat: number, long: number) {

        // Danforth: 43.676173, -79.358705
        // node(around:25, 43.676173, -79.358705); 25meters around lat/long
        // node(around:5000, 43.676173, -79.358705)[amenity=pharmacy];

        var result = await fetch(
            "https://overpass-api.de/api/interpreter",
            {
                method: "POST",
                body: "data=" + encodeURIComponent(`
                    [out:json];
                    node(around:1000, 43.676173, -79.358705)[amenity=restaurant];
                    out;
                `)
            },
        ).then(
            (data) => data.json()
        )

        return result;
    }

}